### PR TITLE
template for global optimization

### PR DESCRIPTION
**Pull request by peisenha**

### CODE REVIEW

**Comment by peisenha** [comment]
@boryana-ilieva , let's briefly discuss this setup before merging tomorrow at our check-in.

**Review by boryana-ilieva — APPROVED** [review]
One thought:
Would it make sense for basecamp and global to share the same resource folder. Now we always have to make sure to copy the newest exogenous information etc into two directories, it might happen than we forget this  at some point and we end up running global and basecamp based on different info.

**Comment by boryana-ilieva** [comment]
Updated bounds for parameters. The values I am least confident in are the bounds for the error variances and the unobserved heterogeneity parameter

**Comment by peisenha** [comment]
Thanks, let's keep the directories separate for now. The idea is that this is just the template where the code is stored that I then start in some other directory anyway, probably just a simple copy of the current `basecamp`.

**Pull request merged**
